name: Build + Push + Update GitOps (single repo)

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  packages: write

jobs:
  build_push_update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set tag
        id: vars
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Debug identity
        run: |
          echo "actor=${{ github.actor }}"
          echo "repo=${{ github.repository }}"
          echo "owner=${{ github.repository_owner }}"

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/dummy-car:${{ steps.vars.outputs.TAG }}
            ghcr.io/${{ github.repository_owner }}/dummy-car:latest

      - name: Debug GitOps paths
        run: |
          echo "PWD=$(pwd)"
          echo "Top-level files/folders:"
          ls -la

          echo "Check if car-gitops exists:"
          ls -la car-gitops || echo "car-gitops folder NOT found"

          echo "Search for overlays folders:"
          find . -maxdepth 6 -type d -name overlays -print || true

          echo "Search for patch.yaml:"
          find . -maxdepth 10 -type f -name patch.yaml -print || true

          echo "Search for kustomization.yaml:"
          find . -maxdepth 10 -type f -name kustomization.yaml -print || true

          echo "Search for dummy-car references:"
          grep -R --line-number "dummy-car" . || true


      - name: Checkout GitOps repo
        uses: actions/checkout@v4
        with:
          repository: bhuvaneswarshweta/car-gitops
          path: car-gitops
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
      


      - name: Update GitOps overlays image tag
        run: |
          TAG=${{ steps.vars.outputs.TAG }}
          OWNER=${{ github.repository_owner }}

          for ENV in dev1 dev2 qa prod; do
            FILE="car-gitops/apps/dummy-car/overlays/${ENV}/patch.yaml"
            sed -i "s#ghcr.io/.*/dummy-car:.*#ghcr.io/${OWNER}/dummy-car:${TAG}#g" "$FILE"
          done

      - name: Commit and push GitOps changes
        run: |
          cd car-gitops

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git status
          git add .

          git commit -m "deploy dummy-car ${{ steps.vars.outputs.TAG }}" || echo "No changes to commit"

          git push

